
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: resilience_db
    ports:
    - "54325:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data1


volumes:
  pgdata: